apiVersion: v1
kind: Namespace
metadata:
  name: students
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-cm
  namespace: students
data:
  init.sql: |
    CREATE USER 'nodeapp' IDENTIFIED WITH mysql_native_password BY 'student12';
    GRANT ALL PRIVILEGES ON *.* TO 'nodeapp'@'%';
    CREATE DATABASE STUDENTS;
    USE STUDENTS;
    CREATE TABLE students(
      id INT NOT NULL AUTO_INCREMENT,
      name VARCHAR(255) NOT NULL,
      address VARCHAR(255) NOT NULL,
      city VARCHAR(255) NOT NULL,
      state VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(100) NOT NULL,
      PRIMARY KEY (id)
    );
---
apiVersion: v1
kind: Pod
metadata:
  name: web-mysql
  namespace: students
  labels:
    app: web-mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-data
          mountPath: /var/lib/mysql
      resources:
        requests: { cpu: "100m", memory: "256Mi" }
        limits:   { cpu: "500m", memory: "512Mi" }
    - name: web
      image: jerry890926/k8s-images:lab-project
      imagePullPolicy: IfNotPresent
      env:
        - name: APP_DB_HOST
          value: "127.0.0.1"
        - name: APP_DB_USER
          value: "nodeapp"
        - name: APP_DB_PASSWORD
          value: "student12"
        - name: APP_DB_NAME
          value: "STUDENTS"
        - name: APP_PORT
          value: "3000"
      ports:
        - containerPort: 3000
      resources:
        requests: { cpu: "100m", memory: "128Mi" }
        limits:   { cpu: "500m", memory: "512Mi" }
  volumes:
    - name: init-sql
      configMap:
        name: init-sql-cm
    - name: mysql-data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-mysql
  namespace: students
spec:
  type: NodePort
  selector:
    app: web-mysql
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
