apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: students
type: Opaque
stringData:
  APP_DB_HOST: "mysql"
  APP_DB_USER: "nodeapp"
  APP_DB_PASSWORD: "student12"
  APP_DB_NAME: "STUDENTS"
  MYSQL_ROOT_PASSWORD: "rootpass"
